#
# * Plugin autorstwa: @To1MaszProblem - https://github.com/To1MaszProblem
#
# * Permisje: [chat.bypass, chat.admin, chat.cmd]
#
# * Plugin wspiera wersje: > 1.16.5
#
chat:
  is-off:
    message: "&8>> &cCzat jest  wyłączony"
    chat-type: "CHAT"
  cancel-message:
    message: "&c&lCHAT &8** &fGracz &c[player] &fpróbował napisać wiadomość, ale chat jest &4wyłączony!"
    chat-type: "CHAT"
message:
  clear:
    sender:
      message: "&aPomyślnie wyczyszczono czat!"
      chat-type: "CHAT"
    broadcast:
      message: "&fCzat został wyczyszczony przez administratora &c[player]"
      chat-type: "CHAT"
  on:
    is-on:
      message: "&8>> &7Chat jest już &awłączony"
      chat-type: "CHAT"
    sender:
      message: "&8>> &7Chat został &awłączony"
      chat-type: "CHAT"
    broadcast:
      message: "&8>> &7Czat został &awłączony &7przez administratora &a[player]"
      chat-type: "CHAT"
  off:
    is-on:
      message: "&8>> &7Chat jest już &cwyłączony"
      chat-type: "CHAT"
    sender:
      message: "&8>> &7Chat został &cwyłączony"
      chat-type: "CHAT"
    broadcast:
      message: "&8>> &7Czat został &cwyłączony &7przez administratora &c[player]"
      chat-type: "CHAT"
chathistory:
  name: "&cWiadomość gracza [player]"
  lore:
    - " "
    - " &8** &fWiadomość: &7[message] &8**"
    - " "